[
  { "name": "Biryani", "image": "biryani.jpg" },
  { "name": "Chicken Biryani", "image": "chicken-biryani.jpg" },
  { "name": "Paneer Butter Masala", "image": "paneer-butter-masala.jpg" },
  { "name": "Butter Chicken", "image": "butter-chicken.jpg" },
  { "name": "Gulab Jamun", "image": "gulab-jamun.jpg" },
  { "name": "Idli Sambar", "image": "idli-sambar.jpg" },
  { "name": "Dosa", "image": "dosa.jpg" },
  { "name": "Vada Pav", "image": "vada-pav.jpg" },
  { "name": "Pav Bhaji", "image": "pav-bhaji.jpg" },
  { "name": "Upma", "image": "upma.jpg" },
  { "name": "Jeera Rice", "image": "jeera-rice.jpg" },
  { "name": "Dal Makhani", "image": "dal-makhani.jpg" },
  { "name": "Rajma Chawal", "image": "rajma-chawal.jpg" },
  { "name": "Chole Bhature", "image": "chole-bhature.jpg" },
  { "name": "Samosa", "image": "samosa.jpg" },
  { "name": "Aloo Paratha", "image": "aloo-paratha.jpg" },
  { "name": "Lassi", "image": "lassi.jpg" },
  { "name": "Mutton Rogan Josh", "image": "mutton-rogan-josh.jpg" },
  { "name": "Fish Curry", "image": "fish-curry.jpg" },
  { "name": "Chicken 65", "image": "chicken-65.jpg" },
  { "name": "Chicken Curry", "image": "chicken-curry.jpg" },
  { "name": "Malai Kofta", "image": "malai-kofta.jpg" },
  { "name": "Kathi Roll", "image": "kathi-roll.jpg" },
  { "name": "Egg Curry", "image": "egg-curry.jpg" },
  { "name": "Curd Rice", "image": "curd-rice.jpg" },
  { "name": "Dhokla", "image": "dhokla.jpg" },
  { "name": "Dahi Puri", "image": "dahi-puri.jpg" },
  { "name": "Bhel Puri", "image": "bhel-puri.jpg" },
  { "name": "Sev Puri", "image": "sev-puri.jpg" },
  { "name": "Aloo Gobi", "image": "aloo-gobi.jpg" },
  { "name": "Bhindi Masala", "image": "bhindi-masala.jpg" },
  { "name": "Baingan Bharta", "image": "baingan-bharta.jpg" },
  { "name": "Palak Paneer", "image": "palak-paneer.jpg" },
  { "name": "Lemon Rice", "image": "lemon-rice.jpg" },
  { "name": "Vegetable Pulao", "image": "veg-pulao.jpg" },
  { "name": "Mix Veg Curry", "image": "mix-veg-curry.jpg" },
  { "name": "Gobi Manchurian", "image": "gobi-manchurian.jpg" },
  { "name": "Fried Rice", "image": "fried-rice.jpg" },
  { "name": "Noodles", "image": "noodles.jpg" },
  { "name": "Manchow Soup", "image": "manchow-soup.jpg" },
  { "name": "Tomato Soup", "image": "tomato-soup.jpg" },
  { "name": "Veg Sandwich", "image": "veg-sandwich.jpg" },
  { "name": "Cheese Pizza", "image": "cheese-pizza.jpg" },
  { "name": "Veg Burger", "image": "veg-burger.jpg" },
  { "name": "Spring Roll", "image": "spring-roll.jpg" },
  { "name": "French Fries", "image": "french-fries.jpg" },
  { "name": "Ice Cream", "image": "ice-cream.jpg" },
  { "name": "Fruit Salad", "image": "fruit-salad.jpg" },
  { "name": "Cold Coffee", "image": "cold-coffee.jpg" }
]
